services:
    stn_rate_limiting.cache.redis_client:
        class: Predis\Client
        public: false

    stn_rate_limiting.listener.rate_limiting:
        class: Stn\RateLimitingBundle\EventListener\RateLimitingListener
        calls:
            - [ setCacheServer, [ @stn_rate_limiting.cache.redis_client ] ]
            - [ setContainer, [ @service_container ]]
            - [ setReader, [ @annotation_reader ]]
        tags:
            # After `RouterListener::onKernelRequest()` which contains a priority 32,
            # since this bundle requires the controller and method information.
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 31 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: monolog.logger, channel: stn.rate_limiting }
